matrix:
  include:
  - os: linux
    language: python
    python: "2.7"
  - os: linux
    language: python
    python: "3.6"
  - os: osx
    language: generic
    python: "2.7"
    env: TRAVIS_PYTHON_VERSION=2.7
  - os: osx
    language: generic
    python: "3.6"
    env: TRAVIS_PYTHON_VERSION=3.6
# Travis builds on Windows fail and this makes the build process very opaque
#  - os: windows
#    language: sh
#    python: "2.7"
#    env: TRAVIS_PYTHON_VERSION=2.7
#  - os: windows
#    language: sh
#    python: "3.6"
#    env: TRAVIS_PYTHON_VERSION=3.6

# Windows builds may not pass due to a TravisCI bug,
# https://travis-ci.community/t/windows-builds-failing-when-using-env-vars/2214.

# We need to install the correct version of Python for MacOS
before_install: |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    pip install virtualenv
    if [ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]; then
      virtualenv -p `which python3` venv
    else
      virtualenv -p `which python2` venv
    fi
    source ./venv/bin/activate
    pip install pip==18.1
  fi
  if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
    if [ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]; then
      choco install python3 --version 3.6.8
      export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
    else
      choco install python2
      export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
      choco install vcpython27
    fi
    python -m pip install --upgrade pip wheel
    pip install pip==18.1
  fi
  python --version
  if [ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]; then
    export PYTHON_VERSION=3
  else
    export PYTHON_VERSION=2
  fi
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    export FILE_NAME="${TRAVIS_OS_NAME}-python${PYTHON_VERSION}-latest-setup"
  else
    export FILE_NAME="${TRAVIS_OS_NAME}-python${PYTHON_VERSION}-${TRAVIS_BRANCH}-setup"
  fi

install:
  - pip install -r requirements.txt

script: |
  if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
    pyinstaller setup.py --add-data "templates/docker-compose.*.yml;templates" --add-data templates/config/*.json;templates/config --add-data "versions.json;." --onefile
  else
    pyinstaller setup.py --add-data templates/docker-compose.*.yml:templates --add-data templates/config/*.json:templates/config --add-data versions.json:. --onefile
  fi
  cp dist/setup "${FILE_NAME}"

# For all commits to a branch, we create draft releases unless they were a pull_request
# For tags, we upload release artefacts to the tagged release
deploy:
  - provider: releases
    api_key: "${GITHUB_OAUTH_TOKEN}"
    file: "${FILE_NAME}"
    name: "${TRAVIS_JOB_NUMBER}-${TRAVIS_BRANCH}"
    body: "Based on commit: ${TRAVIS_COMMIT}"
    skip_cleanup: true
    draft: true
    on:
      tags: false
      all_branches: true
      condition: $TRAVIS_EVENT_TYPE == push
  - provider: releases
    api_key: "${GITHUB_OAUTH_TOKEN}"
    file: "${FILE_NAME}"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
