matrix:
  include:
  - os: linux
    language: python
    python: "2.7"
    env: PYTHON=2.7
  - os: linux
    language: python
    python: "3.4"
    env: PYTHON=3.4
  - os: osx
    language: generic
    python: "2.7"
    env: PYTHON=2.7
  - os: osx
    language: generic
    python: "3.4"
    env: PYTHON=3.4

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    if [ "$PYTHON" == "3.4" ]; then
      brew install python3
      virtualenv env -p python3
      source env/bin/activate
    else
      brew install python2
      virtualenv env -p python2
      source env/bin/activate
    fi
  fi
  python --version

install: |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      python -m pip install -r requirements.txt
    else
      pip install -r requirements.txt
    fi

script:
  - pyinstaller setup.py --add-data templates/docker-compose.*.yml:templates --add-data versions.json:. --onefile
  - cp dist/setup "$TRAVIS_OS_NAME-python$PYTHON-setup"
  - ls *setup

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "$TRAVIS_OS_NAME-python$PYTHON-setup"
  skip_cleanup: true
  draft: true
