# NOTE: The docker-compose.*.yml files need to be configured before the first run by setting all the environment 
# variables and replacing the **public-hostname-or-ip** string with the public hostname or ip of the machine. 
# Please note that this will not work with *localhost* or the docker container hostname because all these servers 
# need to be accessible from the client/browser.

version: '3'
services:
  ovehub-ove-ove:
    image: ovehub/ove:0.2.0
    ports:
    - "8080:8080"

  ovehub-ove-external-tuoris:
    image: ovehub/ove-external-tuoris:v0.1
    ports:
    - "7080:7080"

  ovehub-ove-apps:
    image: ovehub/ove-apps:0.2.0
    depends_on:
      - ovehub-ove-ove
      - ovehub-ove-external-tuoris
    ports:
    - "8081-8089:8081-8089"
    environment:
      OVE_HOST: "public-hostname-or-ip:8080"
      TUORIS_HOST: "public-hostname-or-ip:7080"

