version: '3.1'
services:
  ovehub-ove-ove:
    image: ovehub/ove:${OVE_VERSION}
    volumes:
      - ./config/Spaces.json:/usr/src/app/packages/ove-core/dist/client/Spaces.json:ro

  ovehub-ove-external-tuoris:
    image: ovehub/ove-external-tuoris:${TUORIS_VERSION}
    ports:
    - "7080:7080"

  openvidu-openvidu-call:
    image: openvidu/openvidu-call:${OPENVIDU_VERSION}
    ports:
    - "4443:4443"
    environment:
      openvidu.secret: "${OPENVIDU_SECRET}"
      openvidu.publicurl: "https://${PUBLIC_HOSTNAME}:4443"

  ovehub-ove-service-persistence-inmemory:
    image: ovehub/ove-service-persistence-inmemory:${OVE_SERVICES_VERSION}

  ovehub-ove-apps:
    image: ovehub/ove-apps:${OVE_APPS_VERSION}
    depends_on:
      - ovehub-ove-ove
      - ovehub-ove-external-tuoris
      - openvidu-openvidu-call
    environment:
      OVE_HOST: "${PUBLIC_HOSTNAME}:8080"
      TUORIS_HOST: "${PUBLIC_HOSTNAME}:7080"
      OPENVIDU_HOST: "${PUBLIC_HOSTNAME}:4443"
      OPENVIDU_SECRET: "${OPENVIDU_SECRET}"

  ovehub-ove-ui:
    image: ovehub/ove-ui:${OVE_UI_VERSION}
    depends_on:
      - ovehub-ove-ove
      - ovehub-ove-apps
    volumes:
      - ./config/ove-ui-preview.env:/usr/src/app/packages/ove-ui-preview/.env:ro
      - ./config/ove-ui-launcher.env:/usr/src/app/packages/ove-ui-launcher/.env:ro
      - ./config/ove-ui-status.env:/usr/src/app/packages/ove-ui-status/.env:ro
      - ./config/ove-ui-demo.env:/usr/src/app/packages/ove-ui-demo/.env:ro

  nginx:
    image: nginx:alpine
    depends_on:
      - ovehub-ove-ove
      - ovehub-ove-apps
      - ovehub-ove-service-persistence-inmemory
      - ovehub-ove-ui
    ports:
    - "8080:8080"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
