version: '3.1'
services:
  ovehub-ove-ove:
    image: ovehub/ove:${OVE_VERSION}
    ports:
    - "8080:8080"

  ovehub-ove-external-tuoris:
    image: ovehub/ove-external-tuoris:${TUORIS_VERSION}
    ports:
    - "7080:7080"

  openvidu-openvidu-call:
    image: openvidu/openvidu-call:${OPENVIDU_VERSION}
    ports:
    - "4443:4443"
    environment:
      openvidu.secret: "${OPENVIDU_SECRET}"
      openvidu.publicurl: "https://${PUBLIC_HOSTNAME}:4443"

  ovehub-ove-service-persistence-inmemory:
    image: ovehub/ove-service-persistence-inmemory:${OVE_SERVICES_VERSION}
    ports:
    - "8190:8190"

  ovehub-ove-apps:
    image: ovehub/ove-apps:${OVE_APPS_VERSION}
    depends_on:
      - ovehub-ove-ove
      - ovehub-ove-external-tuoris
      - openvidu-openvidu-call
    ports:
    - "8081-8094:8081-8094"
    environment:
      OVE_HOST: "${PUBLIC_HOSTNAME}:8080"
      TUORIS_HOST: "${PUBLIC_HOSTNAME}:7080"
      OPENVIDU_HOST: "${PUBLIC_HOSTNAME}:4443"
      OPENVIDU_SECRET: "${OPENVIDU_SECRET}"

